spring:
  profiles:
    include:
      - server
      - ocr
      - invite
  application:
    name: Ganhoho
  datasource:
    url: jdbc:mysql://localhost:3306/ganhoho?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: d209
    password: d209
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB



  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: none

  data:
    mongodb:
      uri: mongodb://localhost:27017/ganhoho
      auto-index-creation: true
  mvc:
    dispatch-options-request: true
    dispatch-trace-request: true
  web:
    resources:
      add-mappings: false

springdoc:
  swagger-ui:
    tags-sorter: alpha # 태그 알파벳 순.
    operations-sorter: alpha
  packages-to-scan: com.ssafy.ganhoho
  default-consumes-media-type: application/json
  default-produces-media-type: application/json

server:
  servlet:
    session:
      timeout: 2m



logging:
  pattern:
    console: "%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n"


jwt:
  secret: lcCoZ5lvEmT7BNFMCz9TGgw0zy2lqTSv
  expiration:
    access: 86400000
    refresh: 604800000


fastapi:
  server:
    url: http://localhost:8000

ocr:
  fastapi:
    url: http://localhost:8000

iot:
  token: 9

url:
  https: https_address
  http: http_address
